#!/usr/bin/env bash
# Vérification exécutable réelle des migrations SQL KEEP contre un vrai
# PostgreSQL 16 (pas Supabase lui-même, mais le même moteur avec un schéma
# `auth` minimal qui reproduit le contrat de Supabase Auth -- auth.users +
# auth.uid() lisant request.jwt.claim.sub, comme le fait réellement
# PostgREST/Supabase). Ce n'est PAS une preuve que Supabase fonctionnera à
# l'identique (extensions/policies supplémentaires possibles côté Supabase
# managé), mais une preuve réelle que :
# - toutes les migrations présentes s'appliquent sans erreur, dans l'ordre,
#   sur un moteur PostgreSQL propre ;
# - les triggers métier (is_adult, cohérence devise) produisent le bon
#   résultat, pas seulement "la syntaxe est valide" ;
# - les policies RLS bloquent réellement un accès cross-utilisateur, testé
#   avec un rôle non-superuser (le superuser/propriétaire de table
#   contourne RLS par défaut -- un test qui ignorerait ça ne prouverait rien).
#
# Deux modes de connexion, choisis automatiquement :
# - PGHOST défini (CI GitHub Actions, service postgres:16 en TCP+mot de
#   passe) -> psql direct.
# - PGHOST absent (sandbox local avec un postgresql apt installé, auth par
#   pair Unix) -> `su postgres -c` comme le veut l'auth par pair locale.
#
# Usage: bash supabase/scripts/verify-migrations.sh
set -euo pipefail

DB=keep_verify_ci
PSQL="psql -v ON_ERROR_STOP=1 -X -q"
MIGRATIONS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../migrations" && pwd)"

if [ -n "${PGHOST:-}" ]; then
  pg() { $PSQL "$@"; }
else
  pg() {
    local cmd="$PSQL"
    for a in "$@"; do cmd+=" $(printf '%q' "$a")"; done
    su postgres -c "$cmd"
  }
fi

echo "== Recréation de la base de test =="
pg -c "DROP DATABASE IF EXISTS $DB;" -c "CREATE DATABASE $DB;" >/dev/null

echo "== Shim schéma auth (reproduit le contrat Supabase Auth) =="
pg -d "$DB" <<'SQL'
create extension if not exists pgcrypto;
create schema auth;
-- Colonnes utilisées réellement par les triggers/migrations KEEP. Garder ce
-- shim minimal mais suffisamment fidèle évite qu'un trigger Auth valide en
-- production casse artificiellement le test PostgreSQL local.
create table auth.users (
  id uuid primary key default gen_random_uuid(),
  email text,
  email_confirmed_at timestamptz,
  is_anonymous boolean not null default false,
  raw_user_meta_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create or replace function auth.uid() returns uuid
language sql stable
as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';
-- Supabase expose aussi auth.jwt(). Plusieurs policies récentes lisent
-- is_anonymous depuis les claims ; le CI PostgreSQL doit reproduire ce
-- contrat au lieu de faire échouer une migration valide en production.
create or replace function auth.jwt() returns jsonb
language sql stable
as 'select coalesce(nullif(current_setting(''request.jwt.claims'', true), '''')::jsonb, ''{}''::jsonb)';
drop role if exists anon;
create role anon nosuperuser nobypassrls;
drop role if exists authenticated;
create role authenticated nosuperuser nobypassrls;
drop role if exists service_role;
create role service_role nosuperuser bypassrls;
drop role if exists app_user;
create role app_user nosuperuser nobypassrls login;

-- Supabase crée cette publication managée en production. Le PostgreSQL nu
-- du CI doit la reproduire avant le replay des migrations sans réécrire
-- l'historique SQL de production.
create publication supabase_realtime;

-- Shims des services gérés par Supabase absents de l'image postgres:16
-- générique du CI. Ils ne simulent pas le réseau/scheduler réel ; ils
-- permettent simplement d'exécuter le SQL métier qui les entoure.
create schema if not exists extensions;
create or replace function extensions.gen_random_bytes(p_len integer)
returns bytea language sql volatile
as 'select public.gen_random_bytes(p_len)';
create or replace function extensions.digest(p_data bytea, p_type text)
returns bytea language sql immutable
as 'select public.digest(p_data,p_type)';

create schema if not exists vault;
create table if not exists vault.decrypted_secrets(
  id uuid not null default gen_random_uuid(),
  name text primary key,
  decrypted_secret text not null
);
create or replace function vault.create_secret(
  p_secret text,
  p_name text,
  p_description text default null,
  p_metadata jsonb default null
)
returns uuid
language sql
as 'insert into vault.decrypted_secrets(id,name,decrypted_secret)
    values(gen_random_uuid(),p_name,p_secret)
    on conflict(name) do update set decrypted_secret=excluded.decrypted_secret
    returning id';

create schema if not exists cron;
create table if not exists cron.job(
  jobid bigint generated by default as identity primary key,
  jobname text not null unique,
  schedule text,
  command text
);
create or replace function cron.unschedule(p_jobid bigint)
returns boolean
language sql
as 'delete from cron.job where jobid=p_jobid returning true';
create or replace function cron.schedule(p_jobname text,p_schedule text,p_command text)
returns bigint
language sql
as 'insert into cron.job(jobname,schedule,command) values(p_jobname,p_schedule,p_command)
    on conflict(jobname) do update set schedule=excluded.schedule,command=excluded.command
    returning jobid';
create or replace function cron.alter_job(job_id bigint, command text default null)
returns void
language sql
as 'update cron.job j set command=coalesce($2,j.command) where j.jobid=$1';

-- Shim Supabase Storage : tables/fonction minimales nécessaires aux
-- migrations de buckets/policies. Le stockage réseau réel reste testé sur
-- Supabase, ici on valide uniquement le SQL contre PostgreSQL propre.
create schema if not exists storage;
create table if not exists storage.buckets(
  id text primary key,
  name text not null,
  public boolean not null default false,
  file_size_limit bigint,
  allowed_mime_types text[]
);
create table if not exists storage.objects(
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null references storage.buckets(id) on delete cascade,
  name text not null,
  owner uuid,
  created_at timestamptz not null default now()
);
create or replace function storage.foldername(p_name text)
returns text[]
language sql immutable
as 'select case when p_name is null or p_name = '''' then array[]::text[] else string_to_array(p_name, ''/'') end';
SQL

echo "== Application des migrations (dans l'ordre) =="
for f in "$MIGRATIONS_DIR"/*.sql; do
  name=$(basename "$f")
  echo "  -> $name"

  # Legacy production drift before 20260928000500:
  # production already had Solo progress columns and the two-argument RPC
  # shape before this historical file was recorded. Migration history is
  # immutable, so the replay harness reproduces that pre-existing managed
  # state instead of rewriting an old production migration.
  if [ "$name" = "20260928000500_include_active_solo_players_in_battle_picker.sql" ]; then
    pg -d "$DB" <<'SQL' >/dev/null
alter table public.keep_battle_solo_presence
  add column if not exists solo_round_index integer,
  add column if not exists solo_round_total integer;
drop function if exists public.keep_battle_solo_available(integer,integer);
SQL
  fi

  # Legacy production drift before 20261001120500:
  # admin_event_pending_count() existed in production before the hardening
  # migration that revokes/grants it, but no historical creation migration was
  # recorded. Reproduce the exact live function here; immutable history remains
  # untouched and the current additive migration below documents it canonically.
  if [ "$name" = "20261001120500_harden_admin_rpc_anonymous_access.sql" ]; then
    pg -d "$DB" <<'SQL' >/dev/null
create or replace function public.admin_event_pending_count()
returns integer
language sql
stable
security definer
set search_path to 'public','auth'
as $function$
  select count(*)::integer
  from public.events e
  where e.moderation_status = 'PENDING'
    and e.is_disabled = false
    and public.admin_has_role(auth.uid(), array['SUPER_ADMIN','ADMIN','MODERATOR']);
$function$;
SQL
  fi

  # Drift historique confirmé en production : track_likes.track_id est UUID
  # sur le projet live, alors que la migration 0013 l'avait créé en TEXT.
  # La migration d'affinité musicale s'appuie sur l'état live. On reproduit
  # ce drift dans le replay CI sans réécrire une ancienne migration.
  if [ "$name" = "20261003012200_profile_sale_suggestions_affinity.sql" ]; then
    pg -d "$DB" <<'SQL' >/dev/null
alter table public.track_likes
  alter column track_id type uuid
  using nullif(track_id, '')::uuid;
SQL
  fi

  # Drift historique confirmé avant 20261003223155 :
  # trois migrations Battle silencieuses sont enregistrées sur le projet
  # Supabase live (20261003211526/211544/212245) mais leurs fichiers SQL ne
  # sont plus présents dans le dépôt. Reproduire ici l'état exact de
  # keep_battle_challenge_respond attendu par la migration historique 223155.
  # Ce shim n'écrit jamais en production : il sert uniquement au PostgreSQL
  # éphémère du replay CI; l'historique SQL appliqué reste immuable.
  if [ "$name" = "20261003223155_battle_decline_requires_confirmed_action.sql" ]; then
    pg -d "$DB" <<'SQL' >/dev/null
create or replace function public.keep_battle_challenge_respond(p_challenge_id uuid, p_accept boolean)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  uid uuid:=auth.uid();
  c public.keep_battle_challenges%rowtype;
  a public.keep_battle_arenas%rowtype;
  created jsonb;
  started jsonb;
  aid uuid;
  acode text;
  min_free integer:=3;
  active_count integer:=0;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into c from public.keep_battle_challenges where id=p_challenge_id for update;
  if not found or c.target_id<>uid then raise exception 'BATTLE_CHALLENGE_FORBIDDEN'; end if;

  if c.status='ACCEPTED' then
    if not p_accept then raise exception 'BATTLE_CHALLENGE_ALREADY_ACCEPTED'; end if;
    if c.arena_id is null then raise exception 'BATTLE_ARENA_NOT_FOUND'; end if;
    select * into a from public.keep_battle_arenas where id=c.arena_id;
    if not found then raise exception 'BATTLE_ARENA_NOT_FOUND'; end if;
    return jsonb_build_object('id',c.id,'status','ACCEPTED','arenaId',a.id,'arenaCode',a.arena_code,'themeCode',a.theme_code,'idempotent',true,'arenaState',public.keep_battle_arena_state(a.id));
  end if;

  if c.status='DECLINED' then
    if p_accept then raise exception 'BATTLE_CHALLENGE_ALREADY_DECLINED'; end if;
    return jsonb_build_object('id',c.id,'status','DECLINED','idempotent',true);
  end if;

  if c.status in ('EXPIRED','CANCELLED') then raise exception 'BATTLE_CHALLENGE_EXPIRED'; end if;
  if c.status<>'PENDING' or c.expires_at<=now() then
    update public.keep_battle_challenges set status='EXPIRED',updated_at=now() where id=c.id and status='PENDING';
    raise exception 'BATTLE_CHALLENGE_EXPIRED';
  end if;

  if not p_accept then
    update public.keep_battle_challenges set status='DECLINED',updated_at=now() where id=c.id;
    -- Pas de notification externe/inbox pour un refus : le challenger voit
    -- simplement que le bouton redevient disponible. Évite le doublon avec
    -- le feedback local et le bruit push.
    return jsonb_build_object('id',c.id,'status','DECLINED');
  end if;

  min_free:=public.keep_battle_stake_for_rounds(c.round_count);
  if not public.keep_profile_has_paid_battle_access(c.challenger_id)
     and public.keep_theoretical_free_credit_remaining_for_profile(c.challenger_id)<min_free
  then raise exception 'BATTLE_CHALLENGER_NO_CREDIT:%', min_free; end if;
  if not public.keep_profile_has_paid_battle_access(uid)
     and public.keep_theoretical_free_credit_remaining_for_profile(uid)<min_free
  then raise exception 'BATTLE_ARENA_MINIMUM_THREE_FREE_REQUIRED:%', min_free; end if;

  if c.arena_id is not null then
    select * into a from public.keep_battle_arenas where id=c.arena_id for update;
    if not found then raise exception 'BATTLE_ARENA_NOT_FOUND'; end if;
    if a.status<>'WAITING' or a.expires_at<=now() then raise exception 'BATTLE_ARENA_NOT_OPEN_FOR_INVITES'; end if;
    select count(*) into active_count from public.keep_battle_arena_members where arena_id=a.id and seat_status='ACTIVE';
    if active_count>=a.max_players then raise exception 'BATTLE_ARENA_FULL'; end if;
    if not exists(select 1 from public.keep_battle_arena_members where arena_id=a.id and profile_id=uid and seat_status='ACTIVE') then
      insert into public.keep_battle_arena_members(arena_id,profile_id,seat_status)
      values(a.id,uid,'ACTIVE')
      on conflict(arena_id,profile_id) do update set seat_status='ACTIVE',score=0,correct_predictions=0,total_response_ms=0,placement=null;
      if not public.keep_battle_arena_lock_stake(a.id,a.match_no,uid) then
        update public.keep_battle_arena_members set seat_status='ELIMINATED' where arena_id=a.id and profile_id=uid;
        raise exception 'BATTLE_ARENA_MINIMUM_THREE_FREE_REQUIRED:%', min_free;
      end if;
      perform public.keep_battle_arena_seed_rounds(a.id,a.match_no);
    end if;
    update public.keep_battle_challenges set status='ACCEPTED',updated_at=now() where id=c.id;
    update public.keep_battle_solo_presence set status='SOLO' where profile_id=uid;
    return jsonb_build_object('id',c.id,'status','ACCEPTED','arenaId',a.id,'arenaCode',a.arena_code,'themeCode',a.theme_code,'joinedExistingArena',true,'arenaState',public.keep_battle_arena_state(a.id));
  end if;

  created:=public.keep_battle_arena_create(c.theme_code,c.round_count);
  aid:=(created->>'id')::uuid;
  acode:=created->>'arenaCode';

  insert into public.keep_battle_arena_members(arena_id,profile_id,seat_status)
  values(aid,c.challenger_id,'ACTIVE')
  on conflict(arena_id,profile_id) do update set seat_status='ACTIVE';

  if not public.keep_battle_arena_lock_stake(aid,1,c.challenger_id) then
    raise exception 'BATTLE_CHALLENGER_NO_CREDIT:%', min_free;
  end if;

  perform public.keep_battle_arena_seed_rounds(aid,1);
  update public.keep_battle_challenges set status='ACCEPTED',arena_id=aid,updated_at=now() where id=c.id;
  update public.keep_battle_solo_presence set status='SOLO' where profile_id in(uid,c.challenger_id);
  started:=public.keep_battle_arena_start(aid);

  return jsonb_build_object('id',c.id,'status','ACCEPTED','arenaId',aid,'arenaCode',acode,'themeCode',c.theme_code,'joinedExistingArena',false,'started',true,'arenaState',started);
end;
$function$;
SQL
  fi

  # Supabase fournit pg_cron/pg_net comme extensions managées. Le CI plain
  # PostgreSQL utilise les shims ci-dessus et retire uniquement les deux
  # instructions CREATE EXTENSION qui ne sont pas installables ici.
  sed \
    -e '/^create extension if not exists pg_cron /d' \
    -e '/^create extension if not exists pg_net /d' \
    "$f" | pg -d "$DB" >/dev/null
done

echo "== Droits applicatifs (équivalent du rôle 'authenticated' Supabase) =="
pg -d "$DB" <<'SQL' >/dev/null
grant usage on schema public to app_user;
grant select, insert, update, delete on all tables in schema public to app_user;
grant usage, select on all sequences in schema public to app_user;
SQL

echo "== Assertions métier (triggers + RLS réelle) =="
pg -d "$DB" <<'SQL'
\set ON_ERROR_STOP on
do $$
declare
  user_a uuid := gen_random_uuid();
  user_b uuid := gen_random_uuid();
  admin_id uuid := gen_random_uuid();
  price_id uuid;
  target_plan_id uuid;
  sub_id uuid;
  is_adult_result boolean;
begin
  insert into auth.users (id) values (user_a), (user_b);
  insert into profiles (id, username) values (user_a, 'alice'), (user_b, 'bob');

  insert into auth.users (id) values (admin_id);
  insert into admin_users (id, role) values (admin_id, 'SUPER_ADMIN');

  insert into profile_private_info (profile_id, birth_date) values (user_a, (current_date - interval '20 years')::date);
  select is_adult into is_adult_result from profiles where id = user_a;
  if is_adult_result is not true then
    raise exception 'FAIL is_adult (20 ans) attendu true, obtenu %', is_adult_result;
  end if;
  raise notice 'OK is_adult (20 ans) = true';

  insert into profile_private_info (profile_id, birth_date) values (user_b, (current_date - interval '10 years')::date);
  select is_adult into is_adult_result from profiles where id = user_b;
  if is_adult_result is not false then
    raise exception 'FAIL is_adult (10 ans) attendu false, obtenu %', is_adult_result;
  end if;
  raise notice 'OK is_adult (10 ans) = false';

  select id, plan_id into price_id, target_plan_id from plan_prices where currency_code = 'EUR' limit 1;
  if price_id is null then
    raise exception 'FAIL aucun plan_price EUR trouvé (seed manquant ?)';
  end if;
  insert into subscriptions (id, profile_id, plan_id, plan_price_id, channel, status, country_code, currency_code)
    values (gen_random_uuid(), user_a, target_plan_id, price_id, 'WEB', 'ACTIVE', 'FR', 'EUR')
    returning id into sub_id;
  raise notice 'OK souscription EUR/EUR acceptée';

  begin
    insert into subscriptions (id, profile_id, plan_id, plan_price_id, channel, status, country_code, currency_code)
      values (gen_random_uuid(), user_a, target_plan_id, price_id, 'WEB', 'ACTIVE', 'FR', 'AED');
    raise exception 'FAIL le mélange de devise EUR/AED aurait dû être rejeté par le trigger';
  exception when others then
    if sqlerrm like '%doit correspondre%' then
      raise notice 'OK mélange de devise EUR/AED rejeté par le trigger (%)', sqlerrm;
    else
      raise;
    end if;
  end;
end;
$$;
SQL

echo "== RLS réelle (rôle non-superuser, deux identités simulées) =="
pg -d "$DB" <<'SQL'
set role app_user;
select set_config('request.jwt.claim.sub', (select id::text from profiles where username = 'alice'), true);
do $$
begin
  if not exists (select 1 from profiles where username = 'alice') then
    raise exception 'FAIL Alice ne voit pas son propre profil (RLS trop restrictive)';
  end if;
  raise notice 'OK Alice voit son propre profil';
end;
$$;
do $$
declare
  bob_id uuid;
  leaked_rows int;
begin
  select id into bob_id from profiles where username = 'bob';
  select count(*) into leaked_rows from profile_private_info where profile_id = bob_id;
  if leaked_rows > 0 then
    raise exception 'FAIL fuite RLS : Alice voit % ligne(s) de profile_private_info de Bob', leaked_rows;
  end if;
  raise notice 'OK Alice ne voit pas les infos privées de Bob (0 ligne, RLS effective)';
end;
$$;
do $$
declare
  visible int;
begin
  select count(*) into visible from admin_users;
  if visible > 0 then
    raise exception 'FAIL admin_users visible via un rôle applicatif (% lignes) -- policy admin_users_none inopérante', visible;
  end if;
  raise notice 'OK admin_users invisible via le rôle applicatif (policy admin_users_none effective)';
end;
$$;
reset role;
SQL

echo ""
echo "TOUTES LES ASSERTIONS ONT RÉUSSI (voir 'OK ...' ci-dessus) -- migrations + triggers + RLS vérifiés contre un vrai PostgreSQL 16."
