from pathlib import Path

p = Path('packages/mobile/share-profile.html')
s = p.read_text()

s = s.replace("  const followAccountRoute=(u='')=>`${KEEP_ROOT}?__keep_auth=create${u?`&__keep_follow=${encodeURIComponent(u)}`:''}`;", "  const followAccountRoute=(u='',mode='login')=>`${KEEP_ROOT}?__keep_auth=${encodeURIComponent(mode)}${u?`&__keep_follow=${encodeURIComponent(u)}`:''}&u=${encodeURIComponent(u)}&share=profile`;", 1)

old_rest = """  async function rest(path,options={}){\n    const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...headers,...(options.headers||{})}});\n    if(!response.ok){const body=await response.text().catch(()=> '');throw new Error(`SUPABASE_${response.status}:${body.slice(0,120)}`);}\n    if(response.status===204)return null;return response.json();\n  }"""
new_rest = """  async function rest(path,options={}){\n    const controller=new AbortController();\n    const timer=setTimeout(()=>controller.abort(),10000);\n    try{\n      const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,signal:controller.signal,headers:{...headers,...(options.headers||{})}});\n      if(!response.ok){const body=await response.text().catch(()=> '');throw new Error(`SUPABASE_${response.status}:${body.slice(0,120)}`);}\n      if(response.status===204)return null;return response.json();\n    }finally{clearTimeout(timer);}\n  }"""
if old_rest not in s:
    raise SystemExit('rest anchor missing')
s = s.replace(old_rest, new_rest, 1)

old_follow = """  async function hydrateFollow(p){\n    const button=$('follow'),hint=$('followHint'),session=readSession();\n    if(!session){button.textContent='CRÉER MON COMPTE POUR SUIVRE';button.onclick=()=>{location.href=followAccountRoute(p.username);};return;}\n    if(session.user.id===p.id){button.classList.add('hidden');hint.textContent='Ceci est ton profil public.';return;}\n    async function state(){const rows=await authed(`follows?follower_id=eq.${encodeURIComponent(session.user.id)}&followee_id=eq.${encodeURIComponent(p.id)}&select=follower_id&limit=1`);return Array.isArray(rows)&&rows.length>0;}\n    async function paint(){const on=await state();button.classList.toggle('on',on);button.textContent=on?'ABONNÉ(E)':'+ SUIVRE';hint.textContent=on?'Tu suis ce profil.':'Tu peux suivre ce profil directement.';return on;}\n    button.onclick=async()=>{button.disabled=true;try{const on=await state();if(on)await authed(`follows?follower_id=eq.${encodeURIComponent(session.user.id)}&followee_id=eq.${encodeURIComponent(p.id)}`,{method:'DELETE'});else await authed('follows',{method:'POST',body:JSON.stringify({follower_id:session.user.id,followee_id:p.id}),headers:{Prefer:'return=minimal'}});await paint();}catch{$('followHint').textContent='Suivi momentanément indisponible.';}finally{button.disabled=false;}};\n    await paint().catch(()=>{$('followHint').textContent='Connexion active · suivi momentanément indisponible.';});\n  }"""
new_follow = """  async function hydrateFollow(p){\n    const button=$('follow'),hint=$('followHint'),session=readSession();\n    if(!session){\n      button.textContent='SE CONNECTER / CRÉER POUR SUIVRE';\n      hint.textContent=`Déjà sur KEEP ? Connecte-toi. Sinon crée ton compte : @${p.username} sera suivi automatiquement.`;\n      button.onclick=()=>{location.href=followAccountRoute(p.username,'login');};\n      return;\n    }\n    if(session.user.id===p.id){button.classList.add('hidden');hint.textContent='Ceci est ton profil public.';return;}\n    async function state(){const rows=await authed(`follows?follower_id=eq.${encodeURIComponent(session.user.id)}&followee_id=eq.${encodeURIComponent(p.id)}&select=follower_id&limit=1`);return Array.isArray(rows)&&rows.length>0;}\n    async function paint(){const on=await state();button.classList.toggle('on',on);button.textContent=on?'ABONNÉ(E)':'SUIVRE';hint.textContent=on?'Tu suis ce profil.':'Tu peux suivre ce profil directement.';return on;}\n    button.onclick=async()=>{\n      if(button.disabled)return;\n      button.disabled=true;\n      const previous=button.textContent;\n      button.textContent='UN INSTANT…';\n      try{\n        const on=await state();\n        const auth=authHeaders();\n        if(!auth)throw new Error('NO_SESSION');\n        await rpc(on?'keep_unfollow_profile':'keep_follow_profile',{p_followee_id:p.id},auth);\n        await paint();\n      }catch(error){\n        button.textContent=previous||'SUIVRE';\n        hint.textContent='Le suivi n’a pas abouti. Vérifie ta connexion puis réessaie.';\n      }finally{button.disabled=false;}\n    };\n    await paint().catch(()=>{button.textContent='SUIVRE';hint.textContent='Connexion active · appuie sur SUIVRE pour réessayer.';});\n  }"""
if old_follow not in s:
    raise SystemExit('follow anchor missing')
s = s.replace(old_follow, new_follow, 1)
p.write_text(s)

# Shared links should prefer login for an existing KEEP user instead of forcing account creation.
p = Path('packages/mobile/src/screens/onboarding/OnboardingScreen.tsx')
s = p.read_text()
old = "  const [accountMode, setAccountMode] = useState<UsernameAccountMode>(intent.mode || 'create');"
new = "  const [accountMode, setAccountMode] = useState<UsernameAccountMode>(intent.mode || (intent.followUsername ? 'login' : 'create'));"
if old not in s:
    raise SystemExit('onboarding mode anchor missing')
s = s.replace(old, new, 1)
p.write_text(s)

# Regression contract.
p = Path('packages/mobile/src/screens/__tests__/SharedProfileFollow.contract.test.ts')
p.write_text("""// @ts-nocheck\nimport fs from 'fs';\nimport path from 'path';\n\ndescribe('KEEP shared profile follow handoff', () => {\n  const share = fs.readFileSync(path.resolve(__dirname, '..', '..', '..', 'share-profile.html'), 'utf8');\n  const onboarding = fs.readFileSync(path.resolve(__dirname, '..', 'onboarding', 'OnboardingScreen.tsx'), 'utf8');\n\n  it('never forces an existing user through account creation', () => {\n    expect(share).toContain('SE CONNECTER / CRÉER POUR SUIVRE');\n    expect(share).toContain("followAccountRoute(p.username,'login')");\n    expect(onboarding).toContain("intent.mode || (intent.followUsername ? 'login' : 'create')");\n  });\n\n  it('uses the secured follow RPCs rather than direct follow mutations', () => {\n    expect(share).toContain("on?'keep_unfollow_profile':'keep_follow_profile'");\n    expect(share).not.toContain("await authed('follows',{method:'POST'");\n    expect(share).not.toContain("{method:'DELETE'});else await authed('follows'");\n  });\n\n  it('cannot leave the public follow button locked forever', () => {\n    expect(share).toContain('setTimeout(()=>controller.abort(),10000)');\n    expect(share).toContain('finally{button.disabled=false;}');\n    expect(share).toContain("button.textContent='UN INSTANT…'");\n  });\n\n  it('preserves the shared profile context across login', () => {\n    expect(share).toContain('&share=profile');\n    expect(share).toContain('&u=${encodeURIComponent(u)}');\n    expect(share).toContain('__keep_follow=${encodeURIComponent(u)}');\n  });\n});\n""")
