-- Additive ordering repair for fresh databases.
-- Historical Realtime migrations run before the later private-groups migration,
-- so create the three group relations early with the same canonical schema.
-- The later migration is CREATE TABLE IF NOT EXISTS and remains authoritative
-- for RPCs, indexes and the rest of the private-group feature.

create table if not exists public.music_agora_groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.music_agora_group_members (
  group_id uuid not null references public.music_agora_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'MEMBER' check (role in ('OWNER','MEMBER')),
  status text not null default 'INVITED' check (status in ('INVITED','ACTIVE')),
  invited_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  joined_at timestamptz,
  primary key (group_id, profile_id)
);

create table if not exists public.music_agora_group_messages (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.music_agora_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  shared_track_id uuid references public.tracks(id) on delete set null,
  music_reveal_mode text not null default 'NONE' check (music_reveal_mode in ('NONE','MASKED','FULL')),
  created_at timestamptz not null default now(),
  check (char_length(body) <= 2000),
  check (char_length(btrim(body)) >= 1 or shared_track_id is not null)
);

alter table public.music_agora_groups enable row level security;
alter table public.music_agora_group_members enable row level security;
alter table public.music_agora_group_messages enable row level security;

revoke all on public.music_agora_groups from anon, authenticated;
revoke all on public.music_agora_group_members from anon, authenticated;
revoke all on public.music_agora_group_messages from anon, authenticated;
