-- Deterministic ISO-3166 country catalog fallback. External sync may enrich language_codes later.
insert into public.music_country_catalog(code,name,language_codes,source,updated_at)
values
('AD','Andorra',array[]::text[],'ISO-3166',now()),
('AE','United Arab Emirates',array[]::text[],'ISO-3166',now()),
('AF','Afghanistan',array[]::text[],'ISO-3166',now()),
('AG','Antigua and Barbuda',array[]::text[],'ISO-3166',now()),
('AI','Anguilla',array[]::text[],'ISO-3166',now()),
('AL','Albania',array[]::text[],'ISO-3166',now()),
('AM','Armenia',array[]::text[],'ISO-3166',now()),
('AO','Angola',array[]::text[],'ISO-3166',now()),
('AQ','Antarctica',array[]::text[],'ISO-3166',now()),
('AR','Argentina',array[]::text[],'ISO-3166',now()),
('AS','American Samoa',array[]::text[],'ISO-3166',now()),
('AT','Austria',array[]::text[],'ISO-3166',now()),
('AU','Australia',array[]::text[],'ISO-3166',now()),
('AW','Aruba',array[]::text[],'ISO-3166',now()),
('AX','Åland Islands',array[]::text[],'ISO-3166',now()),
('AZ','Azerbaijan',array[]::text[],'ISO-3166',now()),
('BA','Bosnia and Herzegovina',array[]::text[],'ISO-3166',now()),
('BB','Barbados',array[]::text[],'ISO-3166',now()),
('BD','Bangladesh',array[]::text[],'ISO-3166',now()),
('BE','Belgium',array[]::text[],'ISO-3166',now()),
('BF','Burkina Faso',array[]::text[],'ISO-3166',now()),
('BG','Bulgaria',array[]::text[],'ISO-3166',now()),
('BH','Bahrain',array[]::text[],'ISO-3166',now()),
('BI','Burundi',array[]::text[],'ISO-3166',now()),
('BJ','Benin',array[]::text[],'ISO-3166',now()),
('BL','Saint Barthélemy',array[]::text[],'ISO-3166',now()),
('BM','Bermuda',array[]::text[],'ISO-3166',now()),
('BN','Brunei Darussalam',array[]::text[],'ISO-3166',now()),
('BO','Bolivia, Plurinational State of',array[]::text[],'ISO-3166',now()),
('BQ','Bonaire, Sint Eustatius and Saba',array[]::text[],'ISO-3166',now()),
('BR','Brazil',array[]::text[],'ISO-3166',now()),
('BS','Bahamas',array[]::text[],'ISO-3166',now()),
('BT','Bhutan',array[]::text[],'ISO-3166',now()),
('BV','Bouvet Island',array[]::text[],'ISO-3166',now()),
('BW','Botswana',array[]::text[],'ISO-3166',now()),
('BY','Belarus',array[]::text[],'ISO-3166',now()),
('BZ','Belize',array[]::text[],'ISO-3166',now()),
('CA','Canada',array[]::text[],'ISO-3166',now()),
('CC','Cocos (Keeling) Islands',array[]::text[],'ISO-3166',now()),
('CD','Congo, The Democratic Republic of the',array[]::text[],'ISO-3166',now()),
('CF','Central African Republic',array[]::text[],'ISO-3166',now()),
('CG','Congo',array[]::text[],'ISO-3166',now()),
('CH','Switzerland',array[]::text[],'ISO-3166',now()),
('CI','Côte d''Ivoire',array[]::text[],'ISO-3166',now()),
('CK','Cook Islands',array[]::text[],'ISO-3166',now()),
('CL','Chile',array[]::text[],'ISO-3166',now()),
('CM','Cameroon',array[]::text[],'ISO-3166',now()),
('CN','China',array[]::text[],'ISO-3166',now()),
('CO','Colombia',array[]::text[],'ISO-3166',now()),
('CR','Costa Rica',array[]::text[],'ISO-3166',now()),
('CU','Cuba',array[]::text[],'ISO-3166',now()),
('CV','Cabo Verde',array[]::text[],'ISO-3166',now()),
('CW','Curaçao',array[]::text[],'ISO-3166',now()),
('CX','Christmas Island',array[]::text[],'ISO-3166',now()),
('CY','Cyprus',array[]::text[],'ISO-3166',now()),
('CZ','Czechia',array[]::text[],'ISO-3166',now()),
('DE','Germany',array[]::text[],'ISO-3166',now()),
('DJ','Djibouti',array[]::text[],'ISO-3166',now()),
('DK','Denmark',array[]::text[],'ISO-3166',now()),
('DM','Dominica',array[]::text[],'ISO-3166',now()),
('DO','Dominican Republic',array[]::text[],'ISO-3166',now()),
('DZ','Algeria',array[]::text[],'ISO-3166',now()),
('EC','Ecuador',array[]::text[],'ISO-3166',now()),
('EE','Estonia',array[]::text[],'ISO-3166',now()),
('EG','Egypt',array[]::text[],'ISO-3166',now()),
('EH','Western Sahara',array[]::text[],'ISO-3166',now()),
('ER','Eritrea',array[]::text[],'ISO-3166',now()),
('ES','Spain',array[]::text[],'ISO-3166',now()),
('ET','Ethiopia',array[]::text[],'ISO-3166',now()),
('FI','Finland',array[]::text[],'ISO-3166',now()),
('FJ','Fiji',array[]::text[],'ISO-3166',now()),
('FK','Falkland Islands (Malvinas)',array[]::text[],'ISO-3166',now()),
('FM','Micronesia, Federated States of',array[]::text[],'ISO-3166',now()),
('FO','Faroe Islands',array[]::text[],'ISO-3166',now()),
('FR','France',array[]::text[],'ISO-3166',now()),
('GA','Gabon',array[]::text[],'ISO-3166',now()),
('GB','United Kingdom',array[]::text[],'ISO-3166',now()),
('GD','Grenada',array[]::text[],'ISO-3166',now()),
('GE','Georgia',array[]::text[],'ISO-3166',now()),
('GF','French Guiana',array[]::text[],'ISO-3166',now()),
('GG','Guernsey',array[]::text[],'ISO-3166',now()),
('GH','Ghana',array[]::text[],'ISO-3166',now()),
('GI','Gibraltar',array[]::text[],'ISO-3166',now()),
('GL','Greenland',array[]::text[],'ISO-3166',now()),
('GM','Gambia',array[]::text[],'ISO-3166',now()),
('GN','Guinea',array[]::text[],'ISO-3166',now()),
('GP','Guadeloupe',array[]::text[],'ISO-3166',now()),
('GQ','Equatorial Guinea',array[]::text[],'ISO-3166',now()),
('GR','Greece',array[]::text[],'ISO-3166',now()),
('GS','South Georgia and the South Sandwich Islands',array[]::text[],'ISO-3166',now()),
('GT','Guatemala',array[]::text[],'ISO-3166',now()),
('GU','Guam',array[]::text[],'ISO-3166',now()),
('GW','Guinea-Bissau',array[]::text[],'ISO-3166',now()),
('GY','Guyana',array[]::text[],'ISO-3166',now()),
('HK','Hong Kong',array[]::text[],'ISO-3166',now()),
('HM','Heard Island and McDonald Islands',array[]::text[],'ISO-3166',now()),
('HN','Honduras',array[]::text[],'ISO-3166',now()),
('HR','Croatia',array[]::text[],'ISO-3166',now()),
('HT','Haiti',array[]::text[],'ISO-3166',now()),
('HU','Hungary',array[]::text[],'ISO-3166',now()),
('ID','Indonesia',array[]::text[],'ISO-3166',now()),
('IE','Ireland',array[]::text[],'ISO-3166',now()),
('IL','Israel',array[]::text[],'ISO-3166',now()),
('IM','Isle of Man',array[]::text[],'ISO-3166',now()),
('IN','India',array[]::text[],'ISO-3166',now()),
('IO','British Indian Ocean Territory',array[]::text[],'ISO-3166',now()),
('IQ','Iraq',array[]::text[],'ISO-3166',now()),
('IR','Iran, Islamic Republic of',array[]::text[],'ISO-3166',now()),
('IS','Iceland',array[]::text[],'ISO-3166',now()),
('IT','Italy',array[]::text[],'ISO-3166',now()),
('JE','Jersey',array[]::text[],'ISO-3166',now()),
('JM','Jamaica',array[]::text[],'ISO-3166',now()),
('JO','Jordan',array[]::text[],'ISO-3166',now()),
('JP','Japan',array[]::text[],'ISO-3166',now()),
('KE','Kenya',array[]::text[],'ISO-3166',now()),
('KG','Kyrgyzstan',array[]::text[],'ISO-3166',now()),
('KH','Cambodia',array[]::text[],'ISO-3166',now()),
('KI','Kiribati',array[]::text[],'ISO-3166',now()),
('KM','Comoros',array[]::text[],'ISO-3166',now()),
('KN','Saint Kitts and Nevis',array[]::text[],'ISO-3166',now()),
('KP','Korea, Democratic People''s Republic of',array[]::text[],'ISO-3166',now()),
('KR','Korea, Republic of',array[]::text[],'ISO-3166',now()),
('KW','Kuwait',array[]::text[],'ISO-3166',now()),
('KY','Cayman Islands',array[]::text[],'ISO-3166',now()),
('KZ','Kazakhstan',array[]::text[],'ISO-3166',now()),
('LA','Lao People''s Democratic Republic',array[]::text[],'ISO-3166',now()),
('LB','Lebanon',array[]::text[],'ISO-3166',now()),
('LC','Saint Lucia',array[]::text[],'ISO-3166',now()),
('LI','Liechtenstein',array[]::text[],'ISO-3166',now()),
('LK','Sri Lanka',array[]::text[],'ISO-3166',now()),
('LR','Liberia',array[]::text[],'ISO-3166',now()),
('LS','Lesotho',array[]::text[],'ISO-3166',now()),
('LT','Lithuania',array[]::text[],'ISO-3166',now()),
('LU','Luxembourg',array[]::text[],'ISO-3166',now()),
('LV','Latvia',array[]::text[],'ISO-3166',now()),
('LY','Libya',array[]::text[],'ISO-3166',now()),
('MA','Morocco',array[]::text[],'ISO-3166',now()),
('MC','Monaco',array[]::text[],'ISO-3166',now()),
('MD','Moldova, Republic of',array[]::text[],'ISO-3166',now()),
('ME','Montenegro',array[]::text[],'ISO-3166',now()),
('MF','Saint Martin (French part)',array[]::text[],'ISO-3166',now()),
('MG','Madagascar',array[]::text[],'ISO-3166',now()),
('MH','Marshall Islands',array[]::text[],'ISO-3166',now()),
('MK','North Macedonia',array[]::text[],'ISO-3166',now()),
('ML','Mali',array[]::text[],'ISO-3166',now()),
('MM','Myanmar',array[]::text[],'ISO-3166',now()),
('MN','Mongolia',array[]::text[],'ISO-3166',now()),
('MO','Macao',array[]::text[],'ISO-3166',now()),
('MP','Northern Mariana Islands',array[]::text[],'ISO-3166',now()),
('MQ','Martinique',array[]::text[],'ISO-3166',now()),
('MR','Mauritania',array[]::text[],'ISO-3166',now()),
('MS','Montserrat',array[]::text[],'ISO-3166',now()),
('MT','Malta',array[]::text[],'ISO-3166',now()),
('MU','Mauritius',array[]::text[],'ISO-3166',now()),
('MV','Maldives',array[]::text[],'ISO-3166',now()),
('MW','Malawi',array[]::text[],'ISO-3166',now()),
('MX','Mexico',array[]::text[],'ISO-3166',now()),
('MY','Malaysia',array[]::text[],'ISO-3166',now()),
('MZ','Mozambique',array[]::text[],'ISO-3166',now()),
('NA','Namibia',array[]::text[],'ISO-3166',now()),
('NC','New Caledonia',array[]::text[],'ISO-3166',now()),
('NE','Niger',array[]::text[],'ISO-3166',now()),
('NF','Norfolk Island',array[]::text[],'ISO-3166',now()),
('NG','Nigeria',array[]::text[],'ISO-3166',now()),
('NI','Nicaragua',array[]::text[],'ISO-3166',now()),
('NL','Netherlands',array[]::text[],'ISO-3166',now()),
('NO','Norway',array[]::text[],'ISO-3166',now()),
('NP','Nepal',array[]::text[],'ISO-3166',now()),
('NR','Nauru',array[]::text[],'ISO-3166',now()),
('NU','Niue',array[]::text[],'ISO-3166',now()),
('NZ','New Zealand',array[]::text[],'ISO-3166',now()),
('OM','Oman',array[]::text[],'ISO-3166',now()),
('PA','Panama',array[]::text[],'ISO-3166',now()),
('PE','Peru',array[]::text[],'ISO-3166',now()),
('PF','French Polynesia',array[]::text[],'ISO-3166',now()),
('PG','Papua New Guinea',array[]::text[],'ISO-3166',now()),
('PH','Philippines',array[]::text[],'ISO-3166',now()),
('PK','Pakistan',array[]::text[],'ISO-3166',now()),
('PL','Poland',array[]::text[],'ISO-3166',now()),
('PM','Saint Pierre and Miquelon',array[]::text[],'ISO-3166',now()),
('PN','Pitcairn',array[]::text[],'ISO-3166',now()),
('PR','Puerto Rico',array[]::text[],'ISO-3166',now()),
('PS','Palestine, State of',array[]::text[],'ISO-3166',now()),
('PT','Portugal',array[]::text[],'ISO-3166',now()),
('PW','Palau',array[]::text[],'ISO-3166',now()),
('PY','Paraguay',array[]::text[],'ISO-3166',now()),
('QA','Qatar',array[]::text[],'ISO-3166',now()),
('RE','Réunion',array[]::text[],'ISO-3166',now()),
('RO','Romania',array[]::text[],'ISO-3166',now()),
('RS','Serbia',array[]::text[],'ISO-3166',now()),
('RU','Russian Federation',array[]::text[],'ISO-3166',now()),
('RW','Rwanda',array[]::text[],'ISO-3166',now()),
('SA','Saudi Arabia',array[]::text[],'ISO-3166',now()),
('SB','Solomon Islands',array[]::text[],'ISO-3166',now()),
('SC','Seychelles',array[]::text[],'ISO-3166',now()),
('SD','Sudan',array[]::text[],'ISO-3166',now()),
('SE','Sweden',array[]::text[],'ISO-3166',now()),
('SG','Singapore',array[]::text[],'ISO-3166',now()),
('SH','Saint Helena, Ascension and Tristan da Cunha',array[]::text[],'ISO-3166',now()),
('SI','Slovenia',array[]::text[],'ISO-3166',now()),
('SJ','Svalbard and Jan Mayen',array[]::text[],'ISO-3166',now()),
('SK','Slovakia',array[]::text[],'ISO-3166',now()),
('SL','Sierra Leone',array[]::text[],'ISO-3166',now()),
('SM','San Marino',array[]::text[],'ISO-3166',now()),
('SN','Senegal',array[]::text[],'ISO-3166',now()),
('SO','Somalia',array[]::text[],'ISO-3166',now()),
('SR','Suriname',array[]::text[],'ISO-3166',now()),
('SS','South Sudan',array[]::text[],'ISO-3166',now()),
('ST','Sao Tome and Principe',array[]::text[],'ISO-3166',now()),
('SV','El Salvador',array[]::text[],'ISO-3166',now()),
('SX','Sint Maarten (Dutch part)',array[]::text[],'ISO-3166',now()),
('SY','Syrian Arab Republic',array[]::text[],'ISO-3166',now()),
('SZ','Eswatini',array[]::text[],'ISO-3166',now()),
('TC','Turks and Caicos Islands',array[]::text[],'ISO-3166',now()),
('TD','Chad',array[]::text[],'ISO-3166',now()),
('TF','French Southern Territories',array[]::text[],'ISO-3166',now()),
('TG','Togo',array[]::text[],'ISO-3166',now()),
('TH','Thailand',array[]::text[],'ISO-3166',now()),
('TJ','Tajikistan',array[]::text[],'ISO-3166',now()),
('TK','Tokelau',array[]::text[],'ISO-3166',now()),
('TL','Timor-Leste',array[]::text[],'ISO-3166',now()),
('TM','Turkmenistan',array[]::text[],'ISO-3166',now()),
('TN','Tunisia',array[]::text[],'ISO-3166',now()),
('TO','Tonga',array[]::text[],'ISO-3166',now()),
('TR','Türkiye',array[]::text[],'ISO-3166',now()),
('TT','Trinidad and Tobago',array[]::text[],'ISO-3166',now()),
('TV','Tuvalu',array[]::text[],'ISO-3166',now()),
('TW','Taiwan, Province of China',array[]::text[],'ISO-3166',now()),
('TZ','Tanzania, United Republic of',array[]::text[],'ISO-3166',now()),
('UA','Ukraine',array[]::text[],'ISO-3166',now()),
('UG','Uganda',array[]::text[],'ISO-3166',now()),
('UM','United States Minor Outlying Islands',array[]::text[],'ISO-3166',now()),
('US','United States',array[]::text[],'ISO-3166',now()),
('UY','Uruguay',array[]::text[],'ISO-3166',now()),
('UZ','Uzbekistan',array[]::text[],'ISO-3166',now()),
('VA','Holy See (Vatican City State)',array[]::text[],'ISO-3166',now()),
('VC','Saint Vincent and the Grenadines',array[]::text[],'ISO-3166',now()),
('VE','Venezuela, Bolivarian Republic of',array[]::text[],'ISO-3166',now()),
('VG','Virgin Islands, British',array[]::text[],'ISO-3166',now()),
('VI','Virgin Islands, U.S.',array[]::text[],'ISO-3166',now()),
('VN','Viet Nam',array[]::text[],'ISO-3166',now()),
('VU','Vanuatu',array[]::text[],'ISO-3166',now()),
('WF','Wallis and Futuna',array[]::text[],'ISO-3166',now()),
('WS','Samoa',array[]::text[],'ISO-3166',now()),
('YE','Yemen',array[]::text[],'ISO-3166',now()),
('YT','Mayotte',array[]::text[],'ISO-3166',now()),
('ZA','South Africa',array[]::text[],'ISO-3166',now()),
('ZM','Zambia',array[]::text[],'ISO-3166',now()),
('ZW','Zimbabwe',array[]::text[],'ISO-3166',now())
on conflict(code) do update set name=excluded.name, updated_at=now();
