-- KEEP — catalogue App Store / Google Play + journal de vérification IAP.

create table if not exists public.store_products (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.plans(id) on delete cascade,
  plan_price_id uuid not null references public.plan_prices(id) on delete cascade,
  channel public.payment_channel not null,
  product_id text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint store_products_native_channel check (channel in ('APPLE_IAP','GOOGLE_PLAY_BILLING')),
  constraint store_products_channel_product_unique unique(channel, product_id),
  constraint store_products_price_channel_unique unique(plan_price_id, channel)
);

create index if not exists idx_store_products_plan on public.store_products(plan_id, channel, is_active);

drop trigger if exists trg_store_products_updated_at on public.store_products;
create trigger trg_store_products_updated_at before update on public.store_products
  for each row execute function public.set_updated_at();

alter table public.store_products enable row level security;
drop policy if exists store_products_select_active on public.store_products;
create policy store_products_select_active on public.store_products
  for select using (is_active = true);

insert into public.store_products(plan_id, plan_price_id, channel, product_id, is_active)
select p.id, pp.id, channel::public.payment_channel,
  case p.code::text
    when 'PREMIUM' then 'com.adelkhatra.keep.premium.monthly'
    when 'CREATOR_PRO' then 'com.adelkhatra.keep.creatorpro.monthly'
    when 'VENUE_PRO' then 'com.adelkhatra.keep.venuepro.monthly'
  end,
  true
from public.plans p
join public.plan_prices pp on pp.plan_id=p.id and pp.currency_code='EUR' and pp.period::text='MONTHLY' and pp.is_active=true
cross join (values ('APPLE_IAP'), ('GOOGLE_PLAY_BILLING')) channels(channel)
where p.code::text in ('PREMIUM','CREATOR_PRO','VENUE_PRO')
on conflict (plan_price_id, channel) do update
set product_id=excluded.product_id, is_active=true, updated_at=now();

create table if not exists public.store_purchase_events (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  channel public.payment_channel not null,
  store_transaction_id text,
  store_original_transaction_id text,
  product_id text not null,
  event_type text not null,
  environment text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_store_purchase_events_profile on public.store_purchase_events(profile_id, created_at desc);
create index if not exists idx_store_purchase_events_transaction on public.store_purchase_events(channel, store_transaction_id);
alter table public.store_purchase_events enable row level security;

create unique index if not exists idx_transactions_store_unique
  on public.transactions(channel, store_transaction_id)
  where store_transaction_id is not null;
create unique index if not exists idx_subscriptions_store_original_unique
  on public.subscriptions(channel, store_original_transaction_id)
  where store_original_transaction_id is not null;

create or replace function public.keep_store_product_catalog()
returns table(
  plan_code text,
  plan_name text,
  plan_price_id uuid,
  channel text,
  product_id text,
  currency_code text,
  amount numeric,
  period text,
  trial_days integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.code::text,
    p.name,
    sp.plan_price_id,
    sp.channel::text,
    sp.product_id,
    pp.currency_code::text,
    pp.amount,
    pp.period::text,
    p.trial_days
  from public.store_products sp
  join public.plans p on p.id=sp.plan_id
  join public.plan_prices pp on pp.id=sp.plan_price_id
  where sp.is_active=true and p.is_active=true and pp.is_active=true
  order by p.code::text, sp.channel::text;
$$;

revoke all on function public.keep_store_product_catalog() from public;
grant execute on function public.keep_store_product_catalog() to anon, authenticated;
