create table if not exists public.profile_swipe_listens (
  id bigint generated by default as identity primary key,
  listener_id uuid not null references public.profiles(id) on delete cascade,
  source_profile_id uuid not null references public.profiles(id) on delete cascade,
  track_id uuid not null references public.tracks(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint profile_swipe_listens_not_self check (listener_id <> source_profile_id)
);

alter table public.profile_swipe_listens enable row level security;
revoke all on table public.profile_swipe_listens from anon, authenticated;

create index if not exists idx_profile_swipe_listens_source_created
  on public.profile_swipe_listens(source_profile_id, created_at desc);
create index if not exists idx_profile_swipe_listens_listener_created
  on public.profile_swipe_listens(listener_id, created_at desc);
create index if not exists idx_profile_swipe_listens_track_created
  on public.profile_swipe_listens(track_id, created_at desc);

create or replace function public.keep_profile_swipe_listen_record(
  p_source_profile_id uuid,
  p_track_id uuid
)
returns boolean
language plpgsql
security definer
set search_path to 'public', 'auth'
as $function$
declare
  uid uuid := auth.uid();
  v_is_anonymous boolean := coalesce((auth.jwt()->>'is_anonymous')::boolean, false);
  v_masked uuid[];
begin
  if uid is null or v_is_anonymous then return false; end if;
  if p_source_profile_id is null or p_track_id is null or p_source_profile_id = uid then return false; end if;

  if not exists (
    select 1
    from public.keep_decisions kd
    where kd.profile_id = p_source_profile_id
      and kd.track_id = p_track_id
      and kd.decision = 'KEPT'
      and kd.visibility = 'PUBLIC'
  ) then
    return false;
  end if;

  v_masked := public.keep_playlist_sale_masked_track_ids(p_source_profile_id);
  if p_track_id = any(coalesce(v_masked, array[]::uuid[])) then return false; end if;

  if exists (
    select 1
    from public.profile_swipe_listens l
    where l.listener_id = uid
      and l.source_profile_id = p_source_profile_id
      and l.track_id = p_track_id
      and l.created_at > now() - interval '30 minutes'
  ) then
    return false;
  end if;

  insert into public.profile_swipe_listens(listener_id, source_profile_id, track_id)
  values (uid, p_source_profile_id, p_track_id);

  return true;
end;
$function$;

revoke all on function public.keep_profile_swipe_listen_record(uuid,uuid) from public, anon;
grant execute on function public.keep_profile_swipe_listen_record(uuid,uuid) to authenticated;
