-- Private Loki chat groups live under MESSAGES.
-- Up to 45 people total, including the creator. LA PLACE remains public.

create table if not exists public.music_agora_groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.music_agora_group_members (
  group_id uuid not null references public.music_agora_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'MEMBER' check (role in ('OWNER','MEMBER')),
  status text not null default 'INVITED' check (status in ('INVITED','ACTIVE')),
  invited_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  joined_at timestamptz,
  primary key (group_id, profile_id)
);

create table if not exists public.music_agora_group_messages (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.music_agora_groups(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  shared_track_id uuid references public.tracks(id) on delete set null,
  music_reveal_mode text not null default 'NONE' check (music_reveal_mode in ('NONE','MASKED','FULL')),
  created_at timestamptz not null default now(),
  check (char_length(body) <= 2000),
  check (char_length(btrim(body)) >= 1 or shared_track_id is not null)
);

create index if not exists idx_music_agora_group_members_profile
  on public.music_agora_group_members(profile_id, status, created_at desc);

create index if not exists idx_music_agora_group_messages_group
  on public.music_agora_group_messages(group_id, id desc);

alter table public.music_agora_groups enable row level security;
alter table public.music_agora_group_members enable row level security;
alter table public.music_agora_group_messages enable row level security;

revoke all on public.music_agora_groups from anon, authenticated;
revoke all on public.music_agora_group_members from anon, authenticated;
revoke all on public.music_agora_group_messages from anon, authenticated;

create or replace function public.keep_agora_group_people_search(p_query text default '', p_limit integer default 30)
returns table(profile_id uuid, username text, avatar_url text)
language sql
stable
security definer
set search_path = public, auth
as $$
  select p.id, p.username, p.avatar_url
  from public.profiles p
  where auth.uid() is not null
    and p.id <> auth.uid()
    and p.is_public = true
    and (
      btrim(coalesce(p_query,'')) = ''
      or p.username ilike '%' || replace(replace(btrim(p_query), '%', '\%'), '_', '\_') || '%' escape '\'
      or coalesce(p.display_name,'') ilike '%' || replace(replace(btrim(p_query), '%', '\%'), '_', '\_') || '%' escape '\'
    )
    and not exists (
      select 1 from public.user_blocks b
      where (b.blocker_id = auth.uid() and b.blocked_id = p.id)
         or (b.blocker_id = p.id and b.blocked_id = auth.uid())
    )
  order by
    case when exists (
      select 1 from public.follows f
      where (f.follower_id = auth.uid() and f.followee_id = p.id)
         or (f.followee_id = auth.uid() and f.follower_id = p.id)
    ) then 0 else 1 end,
    lower(p.username)
  limit least(greatest(coalesce(p_limit,30),1),60);
$$;

create or replace function public.keep_agora_create_group(p_name text, p_member_ids uuid[] default '{}'::uuid[])
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_group_id uuid;
  v_clean_name text := left(btrim(coalesce(p_name,'')),80);
  v_member_ids uuid[];
  v_owner_username text;
  v_count integer;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if char_length(v_clean_name) < 1 then raise exception 'group_name_required' using errcode='22023'; end if;

  select coalesce(array_agg(distinct x), '{}'::uuid[])
    into v_member_ids
  from unnest(coalesce(p_member_ids,'{}'::uuid[])) x
  where x is not null and x <> v_uid;

  v_count := coalesce(array_length(v_member_ids,1),0);
  if v_count > 44 then raise exception 'group_member_limit_45' using errcode='22023'; end if;

  if exists (
    select 1
    from unnest(v_member_ids) x
    left join public.profiles p on p.id=x and p.is_public=true
    where p.id is null
  ) then raise exception 'group_member_unavailable' using errcode='22023'; end if;

  insert into public.music_agora_groups(owner_id,name)
  values(v_uid,v_clean_name)
  returning id into v_group_id;

  insert into public.music_agora_group_members(group_id,profile_id,role,status,invited_by,joined_at)
  values(v_group_id,v_uid,'OWNER','ACTIVE',v_uid,now());

  insert into public.music_agora_group_members(group_id,profile_id,role,status,invited_by)
  select v_group_id,x,'MEMBER','INVITED',v_uid
  from unnest(v_member_ids) x
  on conflict (group_id,profile_id) do nothing;

  select username into v_owner_username from public.profiles where id=v_uid;

  insert into public.notifications(profile_id,type,title,body,data,push_delivery_status,push_attempt_count)
  select
    x,
    'AGORA_GROUP_INVITE',
    'Invitation à une conversation',
    '@' || coalesce(v_owner_username,'loki-user') || ' t’invite dans « ' || v_clean_name || ' ».',
    jsonb_build_object('event','AGORA_GROUP_INVITE','groupId',v_group_id,'groupName',v_clean_name,'inviterId',v_uid,'inviterUsername',v_owner_username),
    'CREATED',
    0
  from unnest(v_member_ids) x;

  return v_group_id;
end;
$$;

create or replace function public.keep_agora_my_groups()
returns table(
  group_id uuid,
  group_name text,
  owner_id uuid,
  owner_username text,
  my_role text,
  my_status text,
  member_count integer,
  invited_count integer,
  last_message_id bigint,
  last_body text,
  last_created_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    g.id,
    g.name,
    g.owner_id,
    owner.username,
    me.role,
    me.status,
    (select count(*)::integer from public.music_agora_group_members gm where gm.group_id=g.id and gm.status='ACTIVE'),
    (select count(*)::integer from public.music_agora_group_members gm where gm.group_id=g.id and gm.status='INVITED'),
    lm.id,
    lm.body,
    lm.created_at
  from public.music_agora_group_members me
  join public.music_agora_groups g on g.id=me.group_id
  join public.profiles owner on owner.id=g.owner_id
  left join lateral (
    select m.id,m.body,m.created_at
    from public.music_agora_group_messages m
    where m.group_id=g.id
    order by m.id desc
    limit 1
  ) lm on true
  where me.profile_id=auth.uid()
  order by coalesce(lm.created_at,g.created_at) desc;
$$;

create or replace function public.keep_agora_accept_group(p_group_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  update public.music_agora_group_members
  set status='ACTIVE', joined_at=coalesce(joined_at,now())
  where group_id=p_group_id and profile_id=v_uid and status='INVITED';
  if not found then raise exception 'group_invite_not_found' using errcode='P0002'; end if;
  return true;
end;
$$;

create or replace function public.keep_agora_decline_group(p_group_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  delete from public.music_agora_group_members
  where group_id=p_group_id and profile_id=v_uid and status='INVITED';
  return found;
end;
$$;

create or replace function public.keep_agora_group_members(p_group_id uuid)
returns table(profile_id uuid, username text, avatar_url text, role text, status text)
language sql
stable
security definer
set search_path = public, auth
as $$
  select gm.profile_id,p.username,p.avatar_url,gm.role,gm.status
  from public.music_agora_group_members gm
  join public.profiles p on p.id=gm.profile_id
  where gm.group_id=p_group_id
    and exists (
      select 1 from public.music_agora_group_members me
      where me.group_id=p_group_id and me.profile_id=auth.uid()
    )
  order by case gm.role when 'OWNER' then 0 else 1 end, lower(p.username);
$$;

create or replace function public.keep_agora_invite_group_member(p_group_id uuid, p_profile_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_name text;
  v_username text;
  v_count integer;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if p_profile_id is null or p_profile_id=v_uid then raise exception 'invalid_group_member' using errcode='22023'; end if;

  select g.name into v_name
  from public.music_agora_groups g
  where g.id=p_group_id and g.owner_id=v_uid;
  if v_name is null then raise exception 'group_owner_required' using errcode='42501'; end if;

  select count(*)::integer into v_count
  from public.music_agora_group_members
  where group_id=p_group_id;
  if v_count >= 45 then raise exception 'group_member_limit_45' using errcode='22023'; end if;

  if not exists(select 1 from public.profiles where id=p_profile_id and is_public=true) then
    raise exception 'group_member_unavailable' using errcode='22023';
  end if;

  insert into public.music_agora_group_members(group_id,profile_id,role,status,invited_by)
  values(p_group_id,p_profile_id,'MEMBER','INVITED',v_uid)
  on conflict (group_id,profile_id) do update set status='INVITED', invited_by=v_uid;

  select username into v_username from public.profiles where id=v_uid;
  insert into public.notifications(profile_id,type,title,body,data,push_delivery_status,push_attempt_count)
  values(
    p_profile_id,
    'AGORA_GROUP_INVITE',
    'Invitation à une conversation',
    '@' || coalesce(v_username,'loki-user') || ' t’invite dans « ' || v_name || ' ».',
    jsonb_build_object('event','AGORA_GROUP_INVITE','groupId',p_group_id,'groupName',v_name,'inviterId',v_uid,'inviterUsername',v_username),
    'CREATED',
    0
  );
  return true;
end;
$$;

create or replace function public.keep_agora_remove_group_member(p_group_id uuid, p_profile_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_owner uuid;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  select owner_id into v_owner from public.music_agora_groups where id=p_group_id;
  if v_owner is null then raise exception 'group_not_found' using errcode='P0002'; end if;

  if p_profile_id=v_owner then
    raise exception 'group_owner_cannot_leave' using errcode='22023';
  end if;
  if v_uid<>v_owner and v_uid<>p_profile_id then
    raise exception 'group_owner_required' using errcode='42501';
  end if;

  delete from public.music_agora_group_members
  where group_id=p_group_id and profile_id=p_profile_id;
  return found;
end;
$$;

create or replace function public.keep_agora_group_messages(p_group_id uuid, p_before_id bigint default null, p_limit integer default 30)
returns table(
  id bigint,
  profile_id uuid,
  username text,
  avatar_url text,
  body text,
  created_at timestamptz,
  shared_track_id uuid,
  music_reveal_mode text,
  track_title text,
  track_artist text,
  track_artwork_url text,
  track_preview_url text
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    m.id,
    m.profile_id,
    p.username,
    p.avatar_url,
    m.body,
    m.created_at,
    m.shared_track_id,
    m.music_reveal_mode,
    t.title,
    t.artist,
    t.artwork_url,
    t.preview_url
  from public.music_agora_group_messages m
  join public.profiles p on p.id=m.profile_id
  left join public.tracks t on t.id=m.shared_track_id
  where m.group_id=p_group_id
    and (p_before_id is null or m.id<p_before_id)
    and exists (
      select 1 from public.music_agora_group_members me
      where me.group_id=p_group_id and me.profile_id=auth.uid() and me.status='ACTIVE'
    )
  order by m.id desc
  limit least(greatest(coalesce(p_limit,30),1),100);
$$;

create or replace function public.keep_agora_post_group_message(
  p_group_id uuid,
  p_body text default '',
  p_shared_track_id uuid default null,
  p_reveal_mode text default 'NONE'
)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_body text := btrim(coalesce(p_body,''));
  v_mode text := upper(coalesce(p_reveal_mode,'NONE'));
  v_id bigint;
  v_group_name text;
  v_sender text;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not exists(
    select 1 from public.music_agora_group_members
    where group_id=p_group_id and profile_id=v_uid and status='ACTIVE'
  ) then raise exception 'group_membership_required' using errcode='42501'; end if;

  if p_shared_track_id is null and (char_length(v_body)<1 or char_length(v_body)>2000) then
    raise exception 'message_length' using errcode='22023';
  end if;
  if p_shared_track_id is not null and char_length(v_body)>2000 then
    raise exception 'message_length' using errcode='22023';
  end if;
  if v_body<>'' and public.keep_agora_contains_blocked_language(v_body) then
    raise exception 'message_blocked_language' using errcode='22023';
  end if;
  if v_mode not in ('NONE','MASKED','FULL') then raise exception 'invalid_reveal_mode' using errcode='22023'; end if;
  if p_shared_track_id is null then v_mode:='NONE'; end if;
  if p_shared_track_id is not null and not exists(select 1 from public.tracks where id=p_shared_track_id) then
    raise exception 'track_not_found' using errcode='P0002';
  end if;

  insert into public.music_agora_group_messages(group_id,profile_id,body,shared_track_id,music_reveal_mode)
  values(p_group_id,v_uid,v_body,p_shared_track_id,v_mode)
  returning id into v_id;

  update public.music_agora_groups set updated_at=now() where id=p_group_id;
  select name into v_group_name from public.music_agora_groups where id=p_group_id;
  select username into v_sender from public.profiles where id=v_uid;

  insert into public.notifications(profile_id,type,title,body,data,push_delivery_status,push_attempt_count)
  select
    gm.profile_id,
    'AGORA_GROUP_MESSAGE',
    coalesce(v_group_name,'Conversation'),
    '@' || coalesce(v_sender,'loki-user') || ' a envoyé un message.',
    jsonb_build_object('event','AGORA_GROUP_MESSAGE','groupId',p_group_id,'groupName',v_group_name,'messageId',v_id,'senderId',v_uid,'senderUsername',v_sender),
    'CREATED',
    0
  from public.music_agora_group_members gm
  where gm.group_id=p_group_id and gm.status='ACTIVE' and gm.profile_id<>v_uid;

  return v_id;
end;
$$;

revoke all on function public.keep_agora_group_people_search(text,integer) from public, anon;
grant execute on function public.keep_agora_group_people_search(text,integer) to authenticated;
revoke all on function public.keep_agora_create_group(text,uuid[]) from public, anon;
grant execute on function public.keep_agora_create_group(text,uuid[]) to authenticated;
revoke all on function public.keep_agora_my_groups() from public, anon;
grant execute on function public.keep_agora_my_groups() to authenticated;
revoke all on function public.keep_agora_accept_group(uuid) from public, anon;
grant execute on function public.keep_agora_accept_group(uuid) to authenticated;
revoke all on function public.keep_agora_decline_group(uuid) from public, anon;
grant execute on function public.keep_agora_decline_group(uuid) to authenticated;
revoke all on function public.keep_agora_group_members(uuid) from public, anon;
grant execute on function public.keep_agora_group_members(uuid) to authenticated;
revoke all on function public.keep_agora_invite_group_member(uuid,uuid) from public, anon;
grant execute on function public.keep_agora_invite_group_member(uuid,uuid) to authenticated;
revoke all on function public.keep_agora_remove_group_member(uuid,uuid) from public, anon;
grant execute on function public.keep_agora_remove_group_member(uuid,uuid) to authenticated;
revoke all on function public.keep_agora_group_messages(uuid,bigint,integer) from public, anon;
grant execute on function public.keep_agora_group_messages(uuid,bigint,integer) to authenticated;
revoke all on function public.keep_agora_post_group_message(uuid,text,uuid,text) from public, anon;
grant execute on function public.keep_agora_post_group_message(uuid,text,uuid,text) to authenticated;
