create table if not exists public.music_recognition_attempts (
  id bigint generated by default as identity primary key,
  profile_id uuid null references public.profiles(id) on delete set null,
  device_id_hash text null,
  platform text not null default 'unknown' check (platform in ('ios','android','web','unknown')),
  provider text not null,
  outcome text not null check (outcome in ('MATCH','NO_MATCH','NOT_CONFIGURED','RATE_LIMITED','PROVIDER_ERROR','NETWORK_ERROR','INVALID_AUDIO','OTHER_ERROR')),
  latency_ms integer null check (latency_ms is null or latency_ms >= 0),
  audio_bytes integer null check (audio_bytes is null or audio_bytes >= 0),
  created_at timestamptz not null default now()
);

create index if not exists music_recognition_attempts_platform_created_idx
  on public.music_recognition_attempts(platform, created_at desc);
create index if not exists music_recognition_attempts_provider_created_idx
  on public.music_recognition_attempts(provider, created_at desc);

alter table public.music_recognition_attempts enable row level security;
revoke all on public.music_recognition_attempts from anon, authenticated;

create or replace function public.admin_mobile_recognition_stats(p_hours integer default 168)
returns table(
  platform text,
  provider text,
  attempts bigint,
  matches bigint,
  match_rate numeric,
  avg_latency_ms numeric,
  last_attempt_at timestamptz
)
language sql
security definer
set search_path=public
as $$
  select a.platform,
         a.provider,
         count(*)::bigint,
         count(*) filter (where a.outcome='MATCH')::bigint,
         round(100.0 * count(*) filter (where a.outcome='MATCH') / nullif(count(*),0), 1),
         round(avg(a.latency_ms)::numeric,0),
         max(a.created_at)
  from public.music_recognition_attempts a
  where a.created_at >= now() - make_interval(hours => greatest(1, least(coalesce(p_hours,168), 2160)))
  group by a.platform,a.provider
  order by a.platform,a.provider;
$$;

revoke all on function public.admin_mobile_recognition_stats(integer) from public;
grant execute on function public.admin_mobile_recognition_stats(integer) to service_role;
