-- KEEP — statistiques produit + comptabilité réelle du Super Admin.
-- Aucun mélange de devises : toutes les agrégations financières restent groupées par currency_code.

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  event_name text not null,
  channel text,
  country_code char(2) references public.countries(code),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint product_events_event_name_chk check (event_name in ('profile_share','profile_share_email','playlist_share','compare_share','event_share'))
);
create index if not exists idx_product_events_created_at on public.product_events(created_at desc);
create index if not exists idx_product_events_event_channel on public.product_events(event_name, channel, created_at desc);
create index if not exists idx_product_events_country on public.product_events(country_code, created_at desc);
alter table public.product_events enable row level security;

alter table public.operating_costs add column if not exists country_code char(2) references public.countries(code);
create index if not exists idx_operating_costs_country_date on public.operating_costs(country_code, recorded_at desc);

create or replace function public.track_keep_event(p_event_name text, p_channel text default null, p_metadata jsonb default '{}'::jsonb)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_country char(2);
begin
  if v_uid is null then return false; end if;
  if p_event_name not in ('profile_share','profile_share_email','playlist_share','compare_share','event_share') then
    raise exception 'event_not_allowed';
  end if;
  select p.country_code into v_country from public.profiles p where p.id=v_uid;
  insert into public.product_events(profile_id,event_name,channel,country_code,metadata)
  values(v_uid,p_event_name,nullif(left(btrim(coalesce(p_channel,'')),40),''),v_country,coalesce(p_metadata,'{}'::jsonb));
  return true;
end;
$$;
revoke all on function public.track_keep_event(text,text,jsonb) from public;
grant execute on function public.track_keep_event(text,text,jsonb) to authenticated;

create or replace function public.admin_dashboard_stats(p_from date default (current_date - 29), p_to date default current_date, p_country text default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_from timestamptz;
  v_to timestamptz;
  v_country text := nullif(upper(btrim(coalesce(p_country,''))), '');
  v_result jsonb;
begin
  if not exists(select 1 from public.admin_users a where a.id=v_uid and a.is_active=true) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if p_from is null or p_to is null or p_from > p_to or p_to - p_from > 3660 then raise exception 'invalid_date_range'; end if;
  v_from := p_from::timestamptz;
  v_to := (p_to + 1)::timestamptz;

  select jsonb_build_object(
    'from',p_from,'to',p_to,'country',v_country,
    'usersTotal',(select count(*) from public.profiles p where v_country is null or p.country_code::text=v_country),
    'newUsers',(select count(*) from public.profiles p where p.created_at>=v_from and p.created_at<v_to and (v_country is null or p.country_code::text=v_country)),
    'verifiedEmails',(select count(*) from public.profiles p join auth.users u on u.id=p.id where u.email_confirmed_at is not null and u.email is not null and u.email not like '%@keep.local' and (v_country is null or p.country_code::text=v_country)),
    'activePaid',(select count(distinct s.profile_id) from public.subscriptions s join public.profiles p on p.id=s.profile_id join public.plans pl on pl.id=s.plan_id where s.status in ('ACTIVE'::public.subscription_status,'TRIALING'::public.subscription_status) and pl.code::text<>'FREE' and (s.current_period_end is null or s.current_period_end>now()) and (v_country is null or p.country_code::text=v_country)),
    'keeps',(select count(*) from public.keep_decisions k join public.profiles p on p.id=k.profile_id where k.decision='KEPT' and k.created_at>=v_from and k.created_at<v_to and (v_country is null or p.country_code::text=v_country)),
    'follows',(select count(*) from public.follows f join public.profiles p on p.id=f.follower_id where f.created_at>=v_from and f.created_at<v_to and (v_country is null or p.country_code::text=v_country)),
    'shares',(select count(*) from public.product_events e where e.created_at>=v_from and e.created_at<v_to and (v_country is null or e.country_code::text=v_country)),
    'eventsCreated',(select count(*) from public.events e where e.created_at>=v_from and e.created_at<v_to and (v_country is null or e.country_code::text=v_country)),
    'dailySignups',coalesce((select jsonb_agg(x order by x->>'date') from (select jsonb_build_object('date',d::date,'count',count(p.id)) x from generate_series(p_from,p_to,'1 day'::interval) d left join public.profiles p on p.created_at>=d and p.created_at<d+'1 day'::interval and (v_country is null or p.country_code::text=v_country) group by d) q),'[]'::jsonb),
    'planMix',coalesce((select jsonb_agg(jsonb_build_object('plan',plan_code,'count',cnt) order by plan_code) from (select coalesce(ap.code,'FREE')::text plan_code,count(*) cnt from public.profiles p left join lateral (select pl.code from public.subscriptions s join public.plans pl on pl.id=s.plan_id where s.profile_id=p.id and s.status in ('ACTIVE'::public.subscription_status,'TRIALING'::public.subscription_status) and (s.current_period_end is null or s.current_period_end>now()) order by s.updated_at desc limit 1) ap on true where v_country is null or p.country_code::text=v_country group by coalesce(ap.code,'FREE')) z),'[]'::jsonb),
    'sharesByChannel',coalesce((select jsonb_agg(jsonb_build_object('channel',channel,'count',cnt) order by cnt desc) from (select coalesce(channel,'other') channel,count(*) cnt from public.product_events e where e.created_at>=v_from and e.created_at<v_to and (v_country is null or e.country_code::text=v_country) group by coalesce(channel,'other')) z),'[]'::jsonb),
    'countryMix',coalesce((select jsonb_agg(jsonb_build_object('country',country,'count',cnt) order by cnt desc) from (select coalesce(nullif(p.country_code::text,''),'--') country,count(*) cnt from public.profiles p group by coalesce(nullif(p.country_code::text,''),'--')) z),'[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;
revoke all on function public.admin_dashboard_stats(date,date,text) from public;
grant execute on function public.admin_dashboard_stats(date,date,text) to authenticated;

create or replace function public.admin_finance_report(p_from date default (current_date - 29), p_to date default current_date, p_country text default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_from timestamptz;
  v_to timestamptz;
  v_country text := nullif(upper(btrim(coalesce(p_country,''))), '');
  v_result jsonb;
begin
  if not exists(select 1 from public.admin_users a where a.id=v_uid and a.is_active=true and a.role in ('SUPER_ADMIN'::public.admin_role,'ADMIN'::public.admin_role,'FINANCE'::public.admin_role)) then
    raise exception 'finance_admin_required' using errcode='42501';
  end if;
  if p_from is null or p_to is null or p_from > p_to or p_to - p_from > 3660 then raise exception 'invalid_date_range'; end if;
  v_from := p_from::timestamptz;
  v_to := (p_to + 1)::timestamptz;
  select jsonb_build_object(
    'from',p_from,'to',p_to,'country',v_country,
    'revenueByCurrency',coalesce((select jsonb_agg(jsonb_build_object('currency',currency_code,'gross',gross,'transactions',cnt) order by currency_code) from (select t.currency_code::text currency_code,coalesce(sum(t.amount),0) gross,count(*) cnt from public.transactions t where t.status='SUCCEEDED'::public.transaction_status and t.created_at>=v_from and t.created_at<v_to and (v_country is null or t.country_code::text=v_country) group by t.currency_code) z),'[]'::jsonb),
    'refundsByCurrency',coalesce((select jsonb_agg(jsonb_build_object('currency',currency_code,'amount',amount,'refunds',cnt) order by currency_code) from (select r.currency_code::text currency_code,coalesce(sum(r.amount),0) amount,count(*) cnt from public.refunds r join public.transactions t on t.id=r.transaction_id where r.created_at>=v_from and r.created_at<v_to and (v_country is null or t.country_code::text=v_country) group by r.currency_code) z),'[]'::jsonb),
    'costsByCurrency',coalesce((select jsonb_agg(jsonb_build_object('currency',currency_code,'amount',amount,'entries',cnt) order by currency_code) from (select c.currency_code::text currency_code,coalesce(sum(c.amount),0) amount,count(*) cnt from public.operating_costs c where c.recorded_at>=v_from and c.recorded_at<v_to and (v_country is null or c.country_code::text=v_country) group by c.currency_code) z),'[]'::jsonb),
    'recentTransactions',coalesce((select jsonb_agg(row_data order by created_at desc) from (select t.created_at,jsonb_build_object('id',t.id,'date',t.created_at,'amount',t.amount,'currency',t.currency_code,'country',t.country_code,'status',t.status,'channel',t.channel) row_data from public.transactions t where t.created_at>=v_from and t.created_at<v_to and (v_country is null or t.country_code::text=v_country) order by t.created_at desc limit 100) q),'[]'::jsonb),
    'recentCosts',coalesce((select jsonb_agg(row_data order by recorded_at desc) from (select c.recorded_at,jsonb_build_object('id',c.id,'date',c.recorded_at,'category',c.category,'label',c.label,'amount',c.amount,'currency',c.currency_code,'country',c.country_code,'period',c.period) row_data from public.operating_costs c where c.recorded_at>=v_from and c.recorded_at<v_to and (v_country is null or c.country_code::text=v_country) order by c.recorded_at desc limit 100) q),'[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;
revoke all on function public.admin_finance_report(date,date,text) from public;
grant execute on function public.admin_finance_report(date,date,text) to authenticated;

create or replace function public.admin_record_operating_cost(p_category text,p_label text,p_amount numeric,p_currency_code text,p_period text default 'MONTHLY',p_country text default null,p_recorded_at timestamptz default now())
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_id uuid;
  v_country text := nullif(upper(btrim(coalesce(p_country,''))), '');
begin
  if not exists(select 1 from public.admin_users a where a.id=v_uid and a.is_active=true and a.role in ('SUPER_ADMIN'::public.admin_role,'ADMIN'::public.admin_role,'FINANCE'::public.admin_role)) then raise exception 'finance_admin_required' using errcode='42501'; end if;
  if nullif(btrim(coalesce(p_category,'')),'') is null or nullif(btrim(coalesce(p_label,'')),'') is null then raise exception 'category_and_label_required'; end if;
  if p_amount < 0 then raise exception 'invalid_amount'; end if;
  if not exists(select 1 from public.currencies c where c.code::text=upper(btrim(p_currency_code))) then raise exception 'invalid_currency'; end if;
  if upper(btrim(p_period)) not in ('MONTHLY','YEARLY') then raise exception 'invalid_period'; end if;
  if v_country is not null and not exists(select 1 from public.countries c where c.code::text=v_country) then raise exception 'invalid_country'; end if;
  insert into public.operating_costs(category,label,amount,currency_code,period,recorded_at,created_by,country_code)
  values(left(btrim(p_category),80),left(btrim(p_label),180),p_amount,upper(btrim(p_currency_code))::char(3),upper(btrim(p_period))::public.billing_period,coalesce(p_recorded_at,now()),case when exists(select 1 from public.profiles p where p.id=v_uid) then v_uid else null end,case when v_country is null then null else v_country::char(2) end)
  returning id into v_id;
  insert into public.audit_logs(actor_admin_id,action,target_type,target_id,after) values(v_uid,'operating_cost.created','operating_cost',v_id::text,jsonb_build_object('category',p_category,'label',p_label,'amount',p_amount,'currency',upper(btrim(p_currency_code)),'country',v_country));
  return v_id;
end;
$$;
revoke all on function public.admin_record_operating_cost(text,text,numeric,text,text,text,timestamptz) from public;
grant execute on function public.admin_record_operating_cost(text,text,numeric,text,text,text,timestamptz) to authenticated;

create or replace function public.admin_delete_operating_cost(p_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_deleted int;
begin
  if not exists(select 1 from public.admin_users a where a.id=v_uid and a.is_active=true and a.role in ('SUPER_ADMIN'::public.admin_role,'ADMIN'::public.admin_role,'FINANCE'::public.admin_role)) then raise exception 'finance_admin_required' using errcode='42501'; end if;
  delete from public.operating_costs where id=p_id;
  get diagnostics v_deleted=row_count;
  if v_deleted>0 then insert into public.audit_logs(actor_admin_id,action,target_type,target_id,after) values(v_uid,'operating_cost.deleted','operating_cost',p_id::text,jsonb_build_object('deleted',true)); end if;
  return v_deleted>0;
end;
$$;
revoke all on function public.admin_delete_operating_cost(uuid) from public;
grant execute on function public.admin_delete_operating_cost(uuid) to authenticated;
