create table if not exists public.email_delivery_events (
  id bigint generated by default as identity primary key,
  event_fingerprint text not null unique,
  provider text not null default 'BREVO',
  message_id text,
  recipient_email text not null,
  event_type text not null,
  subject text,
  reason text,
  tags text[] not null default '{}',
  occurred_at timestamptz not null,
  provider_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists email_delivery_events_occurred_at_idx
  on public.email_delivery_events (occurred_at desc);
create index if not exists email_delivery_events_event_type_idx
  on public.email_delivery_events (event_type, occurred_at desc);
create index if not exists email_delivery_events_message_id_idx
  on public.email_delivery_events (message_id)
  where message_id is not null;

alter table public.email_delivery_events enable row level security;
revoke all on public.email_delivery_events from anon, authenticated;
