-- Loki Music Battle: connected presence must stay ON unless the user explicitly
-- disables it; sent invitations stay cancellable for five minutes.
--
-- The large send functions already exist from earlier migrations. Reusing their
-- definitions and changing only the invitation TTL avoids duplicating unrelated
-- business rules (credits, skill gap, group arenas) in this corrective migration.

do $migration$
declare
  ddl text;
begin
  select pg_get_functiondef('public.keep_battle_challenge_send(uuid,text,integer)'::regprocedure) into ddl;
  ddl := replace(ddl, '90 seconds', '5 minutes');
  execute ddl;

  select pg_get_functiondef('public.keep_battle_arena_challenge_send(uuid,uuid)'::regprocedure) into ddl;
  ddl := replace(ddl, '90 seconds', '5 minutes');
  execute ddl;

  select pg_get_functiondef('public.keep_battle_challenge_inbox()'::regprocedure) into ddl;
  ddl := replace(ddl, '90 seconds', '5 minutes');
  execute ddl;
end;
$migration$;

create or replace function public.keep_battle_pending_requires_decision()
returns trigger
language plpgsql
set search_path to 'public'
as $function$
begin
  if new.status = 'PENDING' then
    new.expires_at := least(
      coalesce(new.expires_at, now() + interval '5 minutes'),
      now() + interval '5 minutes'
    );
  end if;
  return new;
end;
$function$;

update public.keep_battle_challenges
set expires_at = greatest(expires_at, created_at + interval '5 minutes'),
    updated_at = now()
where status = 'PENDING'
  and expires_at < created_at + interval '5 minutes';

create table if not exists public.keep_battle_challenge_decision_audit (
  id bigint generated by default as identity primary key,
  challenge_id uuid not null,
  actor_id uuid,
  old_status text,
  new_status text not null,
  created_at timestamptz not null default now()
);

alter table public.keep_battle_challenge_decision_audit enable row level security;

create or replace function public.keep_battle_challenge_audit_status_change()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if old.status is distinct from new.status then
    insert into public.keep_battle_challenge_decision_audit(
      challenge_id, actor_id, old_status, new_status
    ) values (
      new.id, auth.uid(), old.status, new.status
    );
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_keep_battle_challenge_audit_status_change on public.keep_battle_challenges;
create trigger trg_keep_battle_challenge_audit_status_change
after update of status on public.keep_battle_challenges
for each row
execute function public.keep_battle_challenge_audit_status_change();

create or replace function public.keep_battle_challenge_cancel(p_challenge_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  uid uuid := auth.uid();
  c public.keep_battle_challenges%rowtype;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;

  select * into c
  from public.keep_battle_challenges
  where id = p_challenge_id
  for update;

  if not found or c.challenger_id <> uid then
    raise exception 'BATTLE_CHALLENGE_CANCEL_FORBIDDEN';
  end if;

  if c.status = 'CANCELLED' then
    return jsonb_build_object('id', c.id, 'status', 'CANCELLED', 'idempotent', true);
  end if;

  if c.status = 'ACCEPTED' then
    raise exception 'BATTLE_CHALLENGE_ALREADY_ACCEPTED';
  end if;

  if c.status <> 'PENDING' or c.expires_at <= now() then
    if c.status = 'PENDING' then
      update public.keep_battle_challenges
      set status='EXPIRED', updated_at=now()
      where id=c.id;
    end if;
    raise exception 'BATTLE_CHALLENGE_NOT_CANCELLABLE';
  end if;

  update public.keep_battle_challenges
  set status='CANCELLED', updated_at=now()
  where id=c.id;

  delete from public.notifications n
  where n.profile_id = c.target_id
    and n.type in ('BATTLE_CHALLENGE','BATTLE_INVITE')
    and coalesce(n.data->>'challengeId', n.data->>'challenge_id', '') = c.id::text;

  return jsonb_build_object('id', c.id, 'status', 'CANCELLED');
end;
$function$;

revoke all on function public.keep_battle_challenge_cancel(uuid) from public;
grant execute on function public.keep_battle_challenge_cancel(uuid) to authenticated;
